version: "3.8"

volumes:
  postgres:

services:
  postgresql:
    image: postgres:14-alpine
    container_name: rssagg_postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rssagg
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
